# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20171216_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('ACN', 'Accommodation'), ('TRA', 'Transportation'), ('ACT', 'Activity')], max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='service',
            field=models.ManyToManyField(to='trips.Service'),
        ),
    ]
