# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20171219_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Service', max_length=300),
        ),
    ]
