# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='service',
            field=models.ManyToManyField(to='trips.Service', verbose_name='Service'),
        ),
    ]
