# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20171219_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='cost',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='Service', max_length=300, unique=True),
        ),
    ]
