# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20171219_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
